// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package repository

import (
	"context"
)

type Querier interface {
	CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) error
	GetPullRequestByOwnerAndRepositoryAndNumber(ctx context.Context, arg GetPullRequestByOwnerAndRepositoryAndNumberParams) (PullRequest, error)
	ListPullRequests(ctx context.Context) ([]PullRequest, error)
	ListPullRequestsNotNotified(ctx context.Context) ([]PullRequest, error)
	SetNotified(ctx context.Context, arg SetNotifiedParams) error
}

var _ Querier = (*Queries)(nil)
