// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package repository

import (
	"time"
)

type PullRequest struct {
	ID         int64
	Owner      string
	Repository string
	Number     int64
	Notified   bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
